winget install Microsoft.SQLServer.2025.Developer `
  --silent `
  --override "/Q /ACTION=Install /FEATURES=SQLENGINE /INSTANCENAME=MSSQLSERVER /SECURITYMODE=SQL /SAPWD=`"YourStrongPassword123!`" /SQLSYSADMINACCOUNTS=`"$env:USERNAME`" /IACCEPTSQLSERVERLICENSETERMS"
